[global]
	server role = standalone server
	server string = Samba Server Version %v

	# Logging
	log file = /var/log/samba/log.%m
	max log size = 50

	# Miscellaneous
	load printers = no
	strict locking = no

	# Security
	idmap config * : backend = tdb
	security = user
	smb encrypt = desired

	# Protocol
	client ipc max protocol = SMB3
	client ipc min protocol = SMB2
	client max protocol = SMB3
	client min protocol = SMB2

	# Permissions
	create mask = 0664
	directory mask = 0775
	force create mode = 0664
	force directory mode = 0775
	force group = samba

	vfs objects = fruit recycle streams_xattr

	# Apple SMB clients
	fruit:delete_empty_adfiles = yes
	fruit:metadata = stream
	fruit:veto_appledouble = no
	fruit:wipe_intentionally_left_blank_rfork = yes 

	# Recycle Bin
	recycle:keeptree = yes
	recycle:maxsize = 0
	recycle:repository = .recycle
	recycle:versions = yes

[files]
	path = /zpool/files
	read only = no
