require("aerial").setup({
    backends = { "treesitter", "lsp", "markdown", "asciidoc", "man" },
    layout = {
        max_width = { 40, 0.2 },
        width = nil,
        min_width = 20,
        win_opts = {},
        default_direction = "prefer_right",
        placement = "window",
        resize_to_content = true,
        preserve_equality = false,
    },
    attach_mode = "window",
    close_automatic_events = { "unsupported" },
    filter_kind = {
        "Class",
        "Constructor",
        "Enum",
        "Function",
        "Interface",
        "Module",
        "Method",
        "Struct",
    },
    highlight_on_hover = true,
    highlight_on_jump = 300,
    icons = {},
    ignore = {
        unlisted_buffers = true,
        diff_windows = true,
        filetypes = {},
        buftypes = "special",
        wintypes = "special",
    },
    keymaps = {
        ["?"] = "actions.show_help",
        ["g?"] = "actions.show_help",
        ["<CR>"] = "actions.jump",
        ["<2-LeftMouse>"] = "actions.jump",
        ["<C-v>"] = "actions.jump_vsplit",
        ["<C-s>"] = "actions.jump_split",
        ["p"] = "actions.scroll",
        ["<C-j>"] = "actions.down_and_scroll",
        ["<C-k>"] = "actions.up_and_scroll",
        ["{"] = "actions.prev",
        ["}"] = "actions.next",
        ["[["] = "actions.prev_up",
        ["]]"] = "actions.next_up",
        ["q"] = "actions.close",
        ["o"] = "actions.tree_toggle",
        ["O"] = "actions.tree_toggle_recursive",
        ["l"] = "actions.tree_open",
        ["L"] = "actions.tree_open_recursive",
        ["h"] = "actions.tree_close",
        ["H"] = "actions.tree_close_recursive",
        ["zr"] = "actions.tree_increase_fold_level",
        ["zm"] = "actions.tree_reduce_fold_level",
        ["zR"] = "actions.tree_open_all",
        ["zM"] = "actions.tree_close_all",
        ["zx"] = "actions.tree_sync_folds",
        ["za"] = "actions.tree_toggle",
        ["zo"] = "actions.tree_open",
        ["zc"] = "actions.tree_close",
        ["zX"] = "actions.tree_sync_folds",
    },
    show_guides = true,
    guides = {
        mid_item = "├─ ",
        last_item = "└─ ",
        nested_top = "│  ",
        whitespace = "   ",
    },
    float = {
        border = "rounded",
        relative = "win",
        max_height = 0.9,
        height = nil,
        min_height = { 8, 0.1 },
        override = function(conf, _)
            return conf
        end,
    },
    nav = {
        border = "rounded",
        max_height = 0.9,
        min_height = { 10, 0.1 },
        max_width = 0.5,
        min_width = { 0.2, 20 },
        win_opts = {
            cursorline = true,
            winblend = 10,
        },
        autojump = false,
        preview = false,
        keymaps = {
            ["<CR>"] = "actions.jump",
            ["<2-LeftMouse>"] = "actions.jump",
            ["<C-v>"] = "actions.jump_vsplit",
            ["<C-s>"] = "actions.jump_split",
            ["h"] = "actions.left",
            ["l"] = "actions.right",
            ["<C-c>"] = "actions.close",
        },
    },
})

local map = vim.keymap.set
map("n", "<leader>cs", "<cmd>AerialToggle!<cr>", { desc = "Symbol outline" })
