-- Phase 1: Previously installed, now configured
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.blink")
require("plugins.lualine")
require("plugins.oil")
require("plugins.gitsigns")
require("plugins.flash")
require("plugins.which-key")
require("plugins.mini")
require("plugins.conform")
require("plugins.trouble")
require("plugins.aerial")
require("plugins.todo-comments")
require("plugins.indent-blankline")
require("plugins.copilot")
require("plugins.copilot-chat")

-- Phase 2: New plugins
require("plugins.diffview")
require("plugins.dap")
require("plugins.noice")
require("plugins.harpoon")
require("plugins.yanky")
require("plugins.render-markdown")
